controller:
  ingressClassResource:
    name: external-nginx

  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz

  # Required for ACME (cert-manager)
  watchIngressWithoutClass: true

  extraArgs:
    ingress-class: external-nginx
